export interface LoadTestContext {
  domain: string;
  projectName?: string;
  baseUrl?: string;
  targetRPS?: number;
  duration?: string;
  endpoints?: Array<{
    method: string;
    path: string;
    payload?: any;
  }>;
}

export function generateK6Script(ctx: LoadTestContext): string {
  const project = ctx.projectName || `${ctx.domain}-platform`;
  const baseUrl = ctx.baseUrl || 'http://localhost:3000';
  const targetRPS = ctx.targetRPS || 100;
  const duration = ctx.duration || '5m';
  
  const endpoints = ctx.endpoints || [
    { method: 'GET', path: '/api/health' },
    { method: 'GET', path: '/api/users' },
    { method: 'POST', path: '/api/auth/login', payload: { email: 'test@example.com', password: 'password' } },
  ];
  
  return `// k6 Load Test Script for ${project}
// Generated by Intelligent Platform Launcher
// Run: k6 run load-test.js

import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

// Custom metrics
const errorRate = new Rate('errors');
const apiLatency = new Trend('api_latency');
const requestCount = new Counter('requests');

// Test configuration
export const options = {
  stages: [
    { duration: '1m', target: ${Math.floor(targetRPS * 0.25)} },  // Ramp up
    { duration: '2m', target: ${Math.floor(targetRPS * 0.5)} },   // Stay at 50%
    { duration: '2m', target: ${targetRPS} },                      // Full load
    { duration: '${duration}', target: ${targetRPS} },            // Sustained load
    { duration: '1m', target: 0 },                                 // Ramp down
  ],
  thresholds: {
    http_req_duration: ['p(95)<500', 'p(99)<1000'],  // 95th percentile < 500ms
    errors: ['rate<0.01'],                            // Error rate < 1%
    http_req_failed: ['rate<0.01'],                   // HTTP failures < 1%
  },
};

const BASE_URL = __ENV.BASE_URL || '${baseUrl}';
let authToken = '';

// Setup - Run once before tests
export function setup() {
  // Login to get auth token
  const loginRes = http.post(\`\${BASE_URL}/api/auth/login\`, JSON.stringify({
    email: __ENV.TEST_USER || 'test@example.com',
    password: __ENV.TEST_PASS || 'password123',
  }), {
    headers: { 'Content-Type': 'application/json' },
  });
  
  if (loginRes.status === 200) {
    const body = JSON.parse(loginRes.body);
    return { token: body.accessToken };
  }
  
  return { token: '' };
}

// Main test function
export default function(data) {
  const headers = {
    'Content-Type': 'application/json',
    'Authorization': data.token ? \`Bearer \${data.token}\` : '',
  };
  
${endpoints.map((ep, i) => `
  group('${ep.method} ${ep.path}', function() {
    const start = Date.now();
    const res = http.${ep.method.toLowerCase()}(
      \`\${BASE_URL}${ep.path}\`,
      ${ep.payload ? `JSON.stringify(${JSON.stringify(ep.payload)})` : 'null'},
      { headers }
    );
    
    const latency = Date.now() - start;
    apiLatency.add(latency);
    requestCount.add(1);
    
    const success = check(res, {
      'status is 2xx': (r) => r.status >= 200 && r.status < 300,
      'response time < 500ms': (r) => r.timings.duration < 500,
      'has valid response': (r) => r.body.length > 0,
    });
    
    errorRate.add(!success);
    
    sleep(Math.random() * 0.5);
  });
`).join('')}
}

// Teardown - Run once after tests
export function teardown(data) {
  console.log('Load test completed');
}

// Handle summary
export function handleSummary(data) {
  return {
    'summary.json': JSON.stringify(data, null, 2),
    'stdout': textSummary(data, { indent: ' ', enableColors: true }),
  };
}

import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.2/index.js';
`;
}

export function generateJMeterConfig(ctx: LoadTestContext): string {
  const project = ctx.projectName || `${ctx.domain}-platform`;
  const baseUrl = ctx.baseUrl || 'http://localhost:3000';
  const targetRPS = ctx.targetRPS || 100;
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- JMeter Test Plan for ${project} -->
<!-- Generated by Intelligent Platform Launcher -->
<jmeterTestPlan version="1.2" properties="5.0">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="${project} Load Test">
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">
        <collectionProp name="Arguments.arguments">
          <elementProp name="BASE_URL" elementType="Argument">
            <stringProp name="Argument.name">BASE_URL</stringProp>
            <stringProp name="Argument.value">${baseUrl}</stringProp>
          </elementProp>
        </collectionProp>
      </elementProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Users">
        <intProp name="ThreadGroup.num_threads">${targetRPS}</intProp>
        <intProp name="ThreadGroup.ramp_time">60</intProp>
        <longProp name="ThreadGroup.duration">300</longProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="Health Check">
          <stringProp name="HTTPSampler.domain">\${__P(host,localhost)}</stringProp>
          <stringProp name="HTTPSampler.port">\${__P(port,3000)}</stringProp>
          <stringProp name="HTTPSampler.protocol">http</stringProp>
          <stringProp name="HTTPSampler.path">/api/health</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="List Items">
          <stringProp name="HTTPSampler.domain">\${__P(host,localhost)}</stringProp>
          <stringProp name="HTTPSampler.port">\${__P(port,3000)}</stringProp>
          <stringProp name="HTTPSampler.protocol">http</stringProp>
          <stringProp name="HTTPSampler.path">/api/items</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
        </HTTPSamplerProxy>
        <hashTree>
          <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="Headers">
            <collectionProp name="HeaderManager.headers">
              <elementProp name="Authorization" elementType="Header">
                <stringProp name="Header.name">Authorization</stringProp>
                <stringProp name="Header.value">Bearer \${auth_token}</stringProp>
              </elementProp>
            </collectionProp>
          </HeaderManager>
          <hashTree/>
        </hashTree>
        
        <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="Results Tree">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename">results.jtl</stringProp>
        </ResultCollector>
        <hashTree/>
        
        <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <stringProp name="filename">summary.csv</stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
`;
}
